package kiviuq.views;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class MainScreen extends JFrame {

	/**
	 * Auto-generated by eclipse to suppress a warning
	 */
	private static final long serialVersionUID = 1L;
	
	JButton PlayButton = new JButton("Play");

	public MainScreen() {
		super();
		setResizable(false);
		setTitle("Wild Sixes");
		setSize(750, 450);
		setLocationRelativeTo(null);
		getContentPane().setLayout(null);

		JButton ScoreButton = new JButton("Scores");
		ScoreButton.setEnabled(false);
		ScoreButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		ScoreButton.setBounds(10, 359, 131, 52);
		//getContentPane().add(ScoreButton);

//		JButton PlayButton = new JButton("Play");
		PlayButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		PlayButton.setBounds(10, 296, 131, 52);
		PlayButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// Execute when button is pressed
				try {
					MainScreen.this.goToSelectScreen();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}

		});
		getContentPane().add(PlayButton);

		JLabel lblNewLabel = new JLabel("Wild Sixes");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 35));
		lblNewLabel.setBounds(283, 101, 169, 71);
		getContentPane().add(lblNewLabel);
	}

	public void goToSelectScreen() throws ClassNotFoundException, IOException {
		SelectScreen s = new SelectScreen(this);
		s.setVisible(true);
		this.setVisible(false);
	}
}
