package kiviuq.views;

import java.awt.Graphics;

import javax.swing.JPanel;

import kiviuq.entities.Board;
import javax.swing.JLabel;

/**
 * This boundary class is used to visualize a {@link Board}'s score in a
 * {@link JFrame}.
 * 
 * @author Evin Ugur
 *
 */
public class ScoreView extends JPanel {

	/**
	 * auto-generated by eclipse
	 */
	private static final long serialVersionUID = 1L;

	/** Entity object used to represent the current game state */
	Board board;
	/** Label that is used to display the score to the user */
	JLabel lblScoreDisplay;

	/**
	 * Constructs the boundary by adding GUI components and storing entity
	 * objects.
	 * 
	 * @param board
	 *            an object reference to the game.
	 */
	public ScoreView(Board board) {
		super();
		this.board = board;

		JLabel lblScore = new JLabel("Score:");
		add(lblScore);

		this.lblScoreDisplay = new JLabel("Score Display");
		add(lblScoreDisplay);
	}

	/**
	 * Properly paints component to display updated score.
	 */
	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		this.lblScoreDisplay.setText("" + board.getPoints());
	}

}
