package kiviuq.views;

import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * A JFrame that displays Team Kiviuq's names before disappearing and presenting
 * the rest of the application.
 * 
 * @author Evin Ugur
 *
 */
public class SplashScreen extends JFrame {

	/**
	 * Auto-generated by eclipse to suppress a warning
	 */
	private static final long serialVersionUID = 1L;

	/** The amount of time the SplashScreen stays on the screen for */
	int duration_ms;
	/**
	 * The next JFrame to load after the SplashScreen is removed from the
	 * Screen.
	 */
	JFrame nextWindow;

	/**
	 * Constructs a new SplashScreen
	 * @param duration_ms
	 *            amount of time the SplashScreen stays on the screen for.
	 * @param nextWindow
	 *            next JFrame to load after the SplashScreen is removed from the
	 *            Screen. In our main class, the object that is passed in is an
	 *            instance of {@link MainScreen}, however this SplashScreen is
	 *            general purpose enough to work with any JFrame.
	 */
	public SplashScreen(int duration_ms, JFrame nextWindow) {
		super();
		setResizable(false);
		setTitle("Sixes Wild");
		setSize(750, 450);
		setLocationRelativeTo(null); // centers
		this.duration_ms = duration_ms;
		this.nextWindow = nextWindow;
		getContentPane().setLayout(null);

		JLabel lblSixesWild = new JLabel("Sixes Wild - Team Kiviuq");
		lblSixesWild.setFont(new Font("Tahoma", Font.PLAIN, 34));
		lblSixesWild.setBounds(10, 11, 408, 68);
		getContentPane().add(lblSixesWild);

		// have to weirdly use HTML to format JLabels...
		JLabel lblTeamNames = new JLabel(
				"<html>Alyssa Graham<br>Jackson Oliva<br>Molly Homchenko<br>Gabriel Bell<br>Evin Ugur</html>");
		lblTeamNames.setBounds(10, 73, 127, 108);
		getContentPane().add(lblTeamNames);
	}

	/**
	 * After constructing a SplashScreen, call this method to set it off and
	 * have it appear until it is expired.
	 */
	public void launchSplashScreen() {
		setVisible(true);
		try {
			Thread.sleep(duration_ms);
		} catch (Exception e) {
			System.err.println("Could not sleep in splash screen");
		}
		nextWindow.setVisible(true);
		dispose();
	}
}
