package kiviuq.views;

import java.awt.Graphics;

import javax.swing.JPanel;

import kiviuq.entities.StarCriteria;
import javax.swing.JLabel;
import java.awt.GridLayout;

/**
 * Boundary class to visualize a {@link StarCriteria} object in a {@link JFrame}
 * 
 * @author Evin Ugur
 */
public class StarCriteriaView extends JPanel {

	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	/** The Entity object */
	StarCriteria starCriteria;

	/** Label for the one star accomplishment */
	JLabel lblOnecriterialabel;
	/** Label for the two star accomplishment */
	JLabel lblTwocriterialabel;
	/** Label for the three star accomplishment */
	JLabel lblThreecriterialabel;

	/**
	 * Constructs a new StarCriteriaView
	 * 
	 * @param starCriteria
	 *            StarCriteria that displays its information on the view.
	 */
	public StarCriteriaView(StarCriteria starCriteria) {
		super();
		this.starCriteria = starCriteria;

		setLayout(new GridLayout(3, 2, 5, 0));

		JLabel lblOneStar = new JLabel("\u2605");
		add(lblOneStar);

		this.lblOnecriterialabel = new JLabel("OneCriteriaLabel");
		add(lblOnecriterialabel);

		JLabel lblNewLabel = new JLabel("\u2605\u2605");
		add(lblNewLabel);

		this.lblTwocriterialabel = new JLabel("TwoCriteriaLabel");
		add(lblTwocriterialabel);

		JLabel lblThreeStars = new JLabel("\u2605\u2605\u2605");
		add(lblThreeStars);

		this.lblThreecriterialabel = new JLabel("ThreeCriteriaLabel");
		add(lblThreecriterialabel);
	}

	/**
	 * Updates view to properly display the StarCriteria's information.
	 */
	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		lblOnecriterialabel.setText(starCriteria.getPoints1() + "");
		lblTwocriterialabel.setText(starCriteria.getPoints2() + "");
		lblThreecriterialabel.setText(starCriteria.getPoints3() + "");
	}

}
