package kiviuq.views;

import java.awt.Color;
import java.awt.Graphics;

import javax.swing.JLabel;
import javax.swing.JPanel;

import kiviuq.entities.Tile;

public class TileView extends JPanel{

	/**
	 * Auto-generated by eclipse to suppress a warning
	 */
	private static final long serialVersionUID = 1L;
	Tile tile;
	JLabel lblValue;
	JLabel lblMult;
	
	public TileView(Tile tile) {
		super();
		this.tile = tile;
		setSize(50,50);
		setLayout(null);
		
		this.lblValue = new JLabel("VALUE");
		lblValue.setBounds(42, 5, 31, 14);
		add(lblValue);
		
		this.lblMult = new JLabel("MULT");
		lblMult.setBounds(42, 30, 46, 14);
		add(lblMult);
	}
	
	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);	
		if (tile == null) { // just used for testing... 
			setBackground(Color.BLACK);
			return;
		}
		if(this.getTile().isSelected())
			setBackground(Color.WHITE);
		else
			setBackground(getColor());
		lblValue.setText(tile.toString());
		lblMult.setText(tile.multToString());
	}
	
	private final static Color[] NUMBER_COLORS = {Color.ORANGE, Color.CYAN, Color.GREEN, Color.RED, Color.YELLOW, Color.BLUE};
	
	public Color getColor() {
		switch (tile.getType()) {
		case Null:
			return Color.gray;
		case Number:
			int num = tile.getNumber();
			return NUMBER_COLORS[num-1];
		case Release:
			return Color.PINK;
		default:
			return Color.BLACK;
		}
	}
	
	public void setTile(Tile tile) {
		if (this.tile != tile) {
			this.tile = tile;
			this.repaint();
		}
	}
	
	public Tile getTile() {
		return tile;
	}
	
	public JLabel getMainLabel()  {
		return lblValue;
	}
}
